In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/souradippal/fridge-price-prediction-dataset/fridge_price_predictor_dataset_real_brands.csv

In [29]:
data= pd.read_csv('/kaggle/input/datasets/souradippal/fridge-price-prediction-dataset/fridge_price_predictor_dataset_real_brands.csv')
print ((data.duplicated().sum()))

print ('########')
data.head()

0
########

,Brand,Model,Capacity,Energy Rating,Type,Features,Color,Material,Warranty Period,Country of Manufacture,Price,Random Numeric Feature 1,Random Text Feature 2,Irrelevant Category Feature 3
0,Panasonic,Model0,369.0,A++,NaN,NaN,NaN,Stainless Steel,5.0,Germany,1231.0,3984.0,Text0,Category3
1,GE,Model1,619.0,A,Side-by-Side,Smart Connectivity,White,Glass,8.0,Germany,267.0,3155.0,Text1,Category3
2,GE,Model2,309.0,A,Single Door,Ice Dispenser,Black,Stainless Steel,7.0,India,477.0,2218.0,Text2,Category2
3,LG,Model3,662.0,B,Side-by-Side,Ice Dispenser,Gray,Plastic,8.0,India,NaN,4734.0,Text3,Category2
4,Bosch,Model4,533.0,B,Double Door,Water Dispenser,Gray,Plastic,NaN,India,993.0,4259.0,Text4,Category1

splet obj & num

In [19]:
obj_data=data.select_dtypes(include = object)
num_data=data.select_dtypes(exclude = object)

filling null data

In [25]:
clean_obj =obj_data.fillna(obj_data.mode())
clean_obj =clean_obj.fillna('no_value')
clean_num =num_data.fillna(num_data.mean())

In [27]:
clean_obj.info()
clean_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Brand                          20000 non-null  object
 1   Model                          20000 non-null  object
 2   Energy Rating                  20000 non-null  object
 3   Type                           20000 non-null  object
 4   Features                       20000 non-null  object
 5   Color                          20000 non-null  object
 6   Material                       20000 non-null  object
 7   Country of Manufacture         20000 non-null  object
 8   Random Text Feature 2          20000 non-null  object
 9   Irrelevant Category Feature 3  20000 non-null  object
dtypes: object(10)
memory usage: 1.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Capacity                  20000 non-null  float64
 1   Warranty Period           20000 non-null  float64
 2   Price                     20000 non-null  float64
 3   Random Numeric Feature 1  20000 non-null  float64
dtypes: float64(4)
memory usage: 625.1 KB

# concat our data

In [31]:
new_data= pd.concat([clean_obj,clean_num],axis=1)
new_data.head()

,Brand,Model,Energy Rating,Type,Features,Color,Material,Country of Manufacture,Random Text Feature 2,Irrelevant Category Feature 3,Capacity,Warranty Period,Price,Random Numeric Feature 1
0,Panasonic,Model0,A++,Single Door,Smart Connectivity,Silver,Stainless Steel,Germany,Text0,Category3,369.0,5.000000,1231.000000,3984.0
1,GE,Model1,A,Side-by-Side,Smart Connectivity,White,Glass,Germany,Text1,Category3,619.0,8.000000,267.000000,3155.0
2,GE,Model2,A,Single Door,Ice Dispenser,Black,Stainless Steel,India,Text2,Category2,309.0,7.000000,477.000000,2218.0
3,LG,Model3,B,Side-by-Side,Ice Dispenser,Gray,Plastic,India,Text3,Category2,662.0,8.000000,1099.181684,4734.0
4,Bosch,Model4,B,Double Door,Water Dispenser,Gray,Plastic,India,Text4,Category1,533.0,5.022842,993.000000,4259.0

In [33]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Brand                          20000 non-null  object
 1   Model                          20000 non-null  object
 2   Energy Rating                  20000 non-null  object
 3   Type                           20000 non-null  object
 4   Features                       20000 non-null  object
 5   Color                          20000 non-null  object
 6   Material                       20000 non-null  object
 7   Country of Manufacture         20000 non-null  object
 8   Random Text Feature 2          20000 non-null  object
 9   Irrelevant Category Feature 3  20000 non-null  object
 10  Capacity                       20000 non-null  float64
 11  Warranty Period                20000 non-null  float64
 12  Price                          20000 non-null  float64
 13  Random Numeric Feature 1       20000 non-null  float64
dtypes: float64(4), object(10)
memory usage: 2.1+ MB

# data processing obg to num

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
obj_names= clean_obj.columns
for i in obj_names:
    new_data[i]= le.fit_transform(new_data[i])

In [38]:
new_data.head()

,Brand,Model,Energy Rating,Type,Features,Color,Material,Country of Manufacture,Random Text Feature 2,Irrelevant Category Feature 3,Capacity,Warranty Period,Price,Random Numeric Feature 1
0,7,0,2,2,1,2,2,1,0,2,369.0,5.000000,1231.000000,3984.0
1,4,1,0,1,1,3,0,1,1,2,619.0,8.000000,267.000000,3155.0
2,4,10565,0,2,0,0,2,2,10555,1,309.0,7.000000,477.000000,2218.0
3,6,11611,3,1,0,1,1,2,11610,1,662.0,8.000000,1099.181684,4734.0
4,0,12666,3,0,2,1,1,2,12669,0,533.0,5.022842,993.000000,4259.0

In [39]:
new_data.corr()

,Brand,Model,Energy Rating,Type,Features,Color,Material,Country of Manufacture,Random Text Feature 2,Irrelevant Category Feature 3,Capacity,Warranty Period,Price,Random Numeric Feature 1
Brand,1.000000,0.009777,0.003951,-0.001296,0.004569,-0.005155,-0.014403,-0.007163,0.010621,-0.009844,0.015179,0.006268,-0.000952,0.016192
Model,0.009777,1.000000,0.007358,-0.003015,-0.000089,0.002796,-0.000987,0.013089,0.862402,-0.002351,-0.004068,0.001341,0.005543,-0.003674
Energy Rating,0.003951,0.007358,1.000000,0.011829,0.005004,0.000738,0.009285,0.005088,0.008551,-0.008640,-0.005531,-0.004233,0.002964,-0.000802
Type,-0.001296,-0.003015,0.011829,1.000000,-0.013010,-0.001935,-0.009406,-0.006657,-0.007291,-0.016982,0.006516,0.001081,-0.008001,0.006928
Features,0.004569,-0.000089,0.005004,-0.013010,1.000000,-0.010414,-0.004124,-0.000966,-0.008117,0.001437,0.004350,0.004471,-0.017801,-0.000885
Color,-0.005155,0.002796,0.000738,-0.001935,-0.010414,1.000000,-0.004264,0.010039,0.005728,-0.000306,-0.008950,-0.000156,0.000574,-0.002185
Material,-0.014403,-0.000987,0.009285,-0.009406,-0.004124,-0.004264,1.000000,0.003412,0.000298,0.005849,0.003892,0.006203,0.010508,0.012012
Country of Manufacture,-0.007163,0.013089,0.005088,-0.006657,-0.000966,0.010039,0.003412,1.000000,0.011591,0.002994,0.016383,0.001356,0.006567,-0.005499
Random Text Feature 2,0.010621,0.862402,0.008551,-0.007291,-0.008117,0.005728,0.000298,0.011591,1.000000,-0.000845,-0.008041,0.002888,0.005587,-0.002085
Irrelevant Category Feature 3,-0.009844,-0.002351,-0.008640,-0.016982,0.001437,-0.000306,0.005849,0.002994,-0.000845,1.000000,-0.015092,0.006107,-0.002216,0.009597
Capacity,0.015179,-0.004068,-0.005531,0.006516,0.004350,-0.008950,0.003892,0.016383,-0.008041,-0.015092,1.000000,0.004726,-0.006657,0.003363
Warranty Period,0.006268,0.001341,-0.004233,0.001081,0.004471,-0.000156,0.006203,0.001356,0.002888,0.006107,0.004726,1.000000,-0.011922,-0.000289
Price,-0.000952,0.005543,0.002964,-0.008001,-0.017801,0.000574,0.010508,0.006567,0.005587,-0.002216,-0.006657,-0.011922,1.000000,-0.008431
Random Numeric Feature 1,0.016192,-0.003674,-0.000802,0.006928,-0.000885,-0.002185,0.012012,-0.005499,-0.002085,0.009597,0.003363,-0.000289,-0.008431,1.000000

# Split

In [40]:
x= new_data.drop(['Price'], axis=1)
y= new_data['Price']

# training

In [41]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x,y)

LinearRegression()

In [44]:
lr.score(x,y)

0.0008354461520806433